# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.IntegerField()),
                ('word', models.CharField(max_length=255)),
                ('synonims', models.ManyToManyField(related_name='_word_synonims_+', to='quizlet.Word')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizlet.Translation')),
            ],
        ),
    ]
