# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='set_num',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
