# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170311_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Root comment'), (0, 'Usual comment'), (0, 'Deleted comment'), (0, 'Downvoted comment')], default=0),
        ),
        migrations.AlterField(
            model_name='comments_likes',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Dislike'), (1, 'Like')], default=1),
        ),
        migrations.AlterField(
            model_name='posts_likes',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Dislike'), (1, 'Like')], default=1),
        ),
    ]
