# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170323_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postslikes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postslikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostsLikes',
        ),
    ]
