# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170323_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Usual comment'), (2, 'Deleted comment'), (3, 'Downvoted comment')], default=1),
        ),
    ]
