# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0013_auto_20170414_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.IntegerField(blank=True, choices=[(-1, 'Dislike'), (1, 'Like')], default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentslikes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentslikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentsLikes',
        ),
    ]
